INSERT INTO [dbo].[OrderItem	] ([OrderItemId], [OrderId], [ProductId], [Quantity]) VALUES (3, 1500, 2, 5)
INSERT INTO [dbo].[OrderItem	] ([OrderItemId], [OrderId], [ProductId], [Quantity]) VALUES (6, 1600, 10, 50)
INSERT INTO [dbo].[OrderItem	] ([OrderItemId], [OrderId], [ProductId], [Quantity]) VALUES (9, 1700, 8, 20)
INSERT INTO [dbo].[OrderItem	] ([OrderItemId], [OrderId], [ProductId], [Quantity]) VALUES (12, 1800, 4, 10)
INSERT INTO [dbo].[OrderItem	] ([OrderItemId], [OrderId], [ProductId], [Quantity]) VALUES (15, 2000, 6, 100)
